Algoritmo "notas"

Var

   nota1, nota2, media:real

Inicio

      escreva("Digite a primeira nota do aluno: ")
      leia (nota1)
      escreval
      escreva ("Digite a segunda nota do aluno: ")
      leia (nota2)
      media <- nota1 + nota2
      escreval
      escreval ("Nota final = ", media)

      se media < 60 entao
         escreva ("REPROVADO")
      fimse
      

Fimalgoritmo