Algoritmo "troco"



Var

preco, dr, troco:real
quantidade:inteiro

Inicio

      escreva ("Preço unitário do produto: ")
      leia (preco)
      escreval
      escreva ("Quantidade comprada: ")
      leia (quantidade)
      escreval
      escreva ("Dinheiro recebido: ")
      leia (dr)
      escreval



     troco <- dr - (preco * quantidade)

      escreva ("Troco: ", troco:2:2)




Fimalgoritmo